version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  spark:
    image: bitnami/spark:latest
    ports:
      - "4040:4040"
      - "7077:7077"
    environment:
      - SPARK_MODE=master

  producer:
    build:
      context: ./src/kafka
    command: python kafka_producer.py
    depends_on:
      - kafka
