version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    build: .
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      # Định danh duy nhất cho Kafka broker
      KAFKA_BROKER_ID: 1
      # Kết nối tới Zookeeper (sử dụng tên service đã định nghĩa)
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Thiết lập các protocol lắng nghe
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # Định nghĩa các advertised listeners
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      # Số lượng bản sao cho topic hệ thống (nếu chỉ có 1 broker thì đặt là 1)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
