services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Đổi 'kafka' thành hostname broker tuỳ ý, 
      # miễn là trùng với 'container_name' để các service khác truy cập được
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # Ví dụ Kafka Producer
  kafka-producer:
    build:
      context: ./src/kafka
      dockerfile: Dockerfile
    container_name: kafka-producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092  # Sử dụng hostname 'kafka' (tên container) + port 9092

  # Ví dụ Kafka Consumer
  kafka-consumer:
    build:
      context: ./src/kafka
      dockerfile: Dockerfile
    container_name: kafka-consumer
    depends_on:
      - kafka
    command: python kafka_consumer.py
    environment:
      - KAFKA_BROKER=kafka:9092
